filter:
  excluded_paths:
    - tests/*

checks:
  php:
    duplication: false

coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: false
